#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd net.frontuari.recordweight.targetplatform
./plugin-builder $DEBUG_MODE ../net.frontuari.recordweight ../net.frontuari.recordweight.test
